function [] = isGLMokCheck(GLMprm)
% isGLMokCheck(GLMprm) will check if the GLM is ok based on the parameters
% that have been entered. The compatibility of a few parameters will be
% assessed.
%
% INPUTS
% GLMprm: structure with GLM parameters


%% general parameters
Epm = {'Ep','Em'};
RPconditions = {'R','P','RP'};
EsplitConditions = {'E','E1','E2','E3',...
    'Ech0','Ech1','Ech2','Ech3',...
    'lEch','hEch'};

%% if you pool reward and punishments and look at money levels instead of
% money amounts, then the distance between baseline reward and baseline
% punishment might be different across participants but the script will not
% take this into account which may lead to weird results
for iEpm = 1:length(Epm)
    Epm_nm = Epm{iEpm};
    for iEcond = 1:length(EsplitConditions)
        Esplit_nm = EsplitConditions{iEcond};
        if (~strcmp(GLMprm.model_onset.(Epm_nm).choice,'none') &&...
                GLMprm.choice.(Epm_nm).RPpool == 1 &&...
                (ismember(GLMprm.choice.(Epm_nm).RP.(Esplit_nm).money_chosen,[3,4]) ||...
                ismember(GLMprm.choice.(Epm_nm).RP.(Esplit_nm).money_unchosen,[3,4]) ||...
                ismember(GLMprm.choice.(Epm_nm).RP.(Esplit_nm).money_varOption,[3,4]))) ||...
                (~strcmp(GLMprm.model_onset.(Epm_nm).chosen,'none') &&...
                GLMprm.chosen.(Epm_nm).RPpool == 1 &&...
                (ismember(GLMprm.chosen.(Epm_nm).RP.(Esplit_nm).money_chosen,[3,4]) ||...
                ismember(GLMprm.chosen.(Epm_nm).RP.(Esplit_nm).money_varOption,[3,4]) ||...
                ismember(GLMprm.chosen.(Epm_nm).RP.(Esplit_nm).money_unchosen,[3,4]))) ||...
                (~strcmp(GLMprm.model_onset.(Epm_nm).Eperf,'none') &&...
                GLMprm.Eperf.(Epm_nm).RPpool == 1 &&...
                ismember(GLMprm.Eperf.(Epm_nm).RP.(Esplit_nm).money_chosen,[3,4]))
            warning([Epm_nm,' task: You should be cautious in the interpretation',...
                ' of the results because since RPpool = 1, and you look at ',...
                'money levels, the distance between rewards and punishments ',...
                'might be problematic.'])
        end % check for RP and money chosen
    end % E conditions
end % Ep/Em loop

%% % if you look at monetary amounts instead of money levels, you may need to
% % be cautious when interpreting inter-individual differences (a very high
% % beta for money could be just the result of balancing a low amount of money
% % for example)
% for iEpm = 1:length(Epm)
%     Epm_nm = Epm{iEpm};
%     if ismember(GLMprm.choice.(Epm_nm).money_chosen,[1,2]) ||...
%             ismember(GLMprm.choice.(Epm_nm).money_unchosen,[1,2]) ||...
%             ismember(GLMprm.choice.(Epm_nm).money_varOption,[1,2]) ||...
%             ismember(GLMprm.chosen.(Epm_nm).money_chosen,[1,2]) ||...
%             ismember(GLMprm.chosen.(Epm_nm).money_varOption,[1,2]) ||...
%             ismember(GLMprm.chosen.(Epm_nm).money_unchosen,[1,2]) ||...
%             ismember(GLMprm.Eperf.(Epm_nm).money_chosen,[1,2])
%         warning([Epm_nm,' task: you should be cautious in interpreting ',...
%             'interindividual differences since actual monetary amounts were ',...
%             'entered.']);
%     end % check for money amounts
% end % Ep/Em loop

%% net value models
for iEpm = 1:length(Epm)
    Epm_nm = Epm{iEpm};
    for iRP = 1:length(RPconditions)
        RP_nm = RPconditions{iRP};
        for iEcond = 1:length(EsplitConditions)
            Esplit_nm = EsplitConditions{iEcond};
            if ((GLMprm.choice.(Epm_nm).(RP_nm).(Esplit_nm).NV_chosen ~= 0 ||...
                    GLMprm.choice.(Epm_nm).(RP_nm).(Esplit_nm).NV_varOption ~= 0) &&...
                    isempty(GLMprm.choice.(Epm_nm).(RP_nm).(Esplit_nm).NV_mdl)) ||...
                    ((GLMprm.chosen.(Epm_nm).(RP_nm).(Esplit_nm).NV_chosen ~= 0 ||...
                    GLMprm.chosen.(Epm_nm).(RP_nm).(Esplit_nm).NV_varOption ~= 0) &&...
                    isempty(GLMprm.chosen.(Epm_nm).(RP_nm).(Esplit_nm).NV_mdl)) ||...
                    ((GLMprm.Eperf.(Epm_nm).(RP_nm).(Esplit_nm).NV_chosen ~= 0 ||...
                    GLMprm.Eperf.(Epm_nm).(RP_nm).(Esplit_nm).NV_varOption ~= 0) &&...
                    isempty(GLMprm.Eperf.(Epm_nm).(RP_nm).(Esplit_nm).NV_mdl))
                error(['you added net value in the model but you didn''t ',...
                    'specify the model number to use. Please fix it.']);
            end % check
        end % E conditions
    end % RP loop
end % Ep/Em loop

end % function