%% look at performance depending on ROI (perf_f_ROI.m) and then split 
% depending on a metabolite selected by yourself

%% load performance in function of ROI
perf_f_ROI;
close all;

%% load group indexes depending on the level of metabolites
[met_subs.low, met_subs.high, metabolite_nm, ROI_nm] = medSplit_metabolites(study_nm, subject_id);
met_groups = {'low','high'};
n_met_grps = length(met_groups);
%% average data according to which group (low/high metabolite)
% basic data
for iGrp = 1:n_met_grps
    grp_nm = met_groups{iGrp};
    grp_nm_bis = [grp_nm,'_',metabolite_nm];
    
    for iTask = 1:nTasks
        task_nm = task_names{iTask};
        % effort chosen
        [m_ROI_activity_mbSplit.(task_nm).perEch.(grp_nm_bis),...
            sem_ROI_activity_mbSplit.(task_nm).perEch.(grp_nm_bis)] = mean_sem_sd(ROI_activity.(task_nm).perEch(:,met_subs.(grp_nm)), 2);
        [m_ROI_activity_mbSplit.(task_nm).choice_highE.perHighElevel.(grp_nm_bis),...
            sem_ROI_activity_mbSplit.(task_nm).choice_highE.perHighElevel.(grp_nm_bis)] = mean_sem_sd(ROI_activity.(task_nm).choice_highE.perHighElevel(:,met_subs.(grp_nm)), 2);
        [m_ROI_activity_mbSplit.(task_nm).choice_lowE.perHighElevel.(grp_nm_bis),...
            sem_ROI_activity_mbSplit.(task_nm).choice_lowE.perHighElevel.(grp_nm_bis)] = mean_sem_sd(ROI_activity.(task_nm).choice_lowE.perHighElevel(:,met_subs.(grp_nm)), 2);
    end % task loop
        %% loop through levels of activity of the ROI
        ROI_level = {'low','high'};
        for iROI_lvl = 1:length(ROI_level)
            ROI_info_nm = [ROI_level{iROI_lvl},'_',ROI_short_nm];
            
            % E chosen
            % physical
            [m_perf_mbSplit.physical.latency.perEch.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.physical.latency.perEch.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.physical.latency.perEch.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.physical.AUC.perEch.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.physical.AUC.perEch.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.physical.AUC.perEch.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.physical.forcePeak.perEch.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.physical.forcePeak.perEch.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.physical.forcePeak.perEch.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.physical.AUC_overshoot.perEch.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.physical.AUC_overshoot.perEch.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.physical.AUC_overshoot.perEch.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.physical.perf.perEch.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.physical.perf.perEch.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.physical.perf.perEch.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            % mental
            [m_perf_mbSplit.mental.n_errors.perEch.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.mental.n_errors.perEch.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.mental.n_errors.perEch.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.mental.successSpeed.perEch.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.mental.successSpeed.perEch.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.mental.successSpeed.perEch.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.mental.perf.perEch.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.mental.perf.perEch.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.mental.perf.perEch.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.mental.RT_avg.perEch.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.mental.RT_avg.perEch.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.mental.RT_avg.perEch.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            
            % low effort chosen
            % physical
            [m_perf_mbSplit.physical.latency.choice_lowE.perHighElevel.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.physical.latency.choice_lowE.perHighElevel.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.physical.latency.choice_lowE.perHighElevel.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.physical.AUC.choice_lowE.perHighElevel.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.physical.AUC.choice_lowE.perHighElevel.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.physical.AUC.choice_lowE.perHighElevel.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.physical.forcePeak.choice_lowE.perHighElevel.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.physical.forcePeak.choice_lowE.perHighElevel.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.physical.forcePeak.choice_lowE.perHighElevel.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.physical.AUC_overshoot.choice_lowE.perHighElevel.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.physical.AUC_overshoot.choice_lowE.perHighElevel.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.physical.AUC_overshoot.choice_lowE.perHighElevel.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.physical.perf.choice_lowE.perHighElevel.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.physical.perf.choice_lowE.perHighElevel.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.physical.perf.choice_lowE.perHighElevel.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            % mental
            [m_perf_mbSplit.mental.n_errors.choice_lowE.perHighElevel.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.mental.n_errors.choice_lowE.perHighElevel.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.mental.n_errors.choice_lowE.perHighElevel.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.mental.successSpeed.choice_lowE.perHighElevel.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.mental.successSpeed.choice_lowE.perHighElevel.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.mental.successSpeed.choice_lowE.perHighElevel.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.mental.perf.choice_lowE.perHighElevel.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.mental.perf.choice_lowE.perHighElevel.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.mental.perf.choice_lowE.perHighElevel.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.mental.RT_avg.choice_lowE.perHighElevel.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.mental.RT_avg.choice_lowE.perHighElevel.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.mental.RT_avg.choice_lowE.perHighElevel.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            
            % high effort chosen
            % physical
            [m_perf_mbSplit.physical.latency.choice_highE.perHighElevel.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.physical.latency.choice_highE.perHighElevel.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.physical.latency.choice_highE.perHighElevel.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.physical.AUC.choice_highE.perHighElevel.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.physical.AUC.choice_highE.perHighElevel.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.physical.AUC.choice_highE.perHighElevel.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.physical.forcePeak.choice_highE.perHighElevel.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.physical.forcePeak.choice_highE.perHighElevel.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.physical.forcePeak.choice_highE.perHighElevel.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.physical.AUC_overshoot.choice_highE.perHighElevel.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.physical.AUC_overshoot.choice_highE.perHighElevel.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.physical.AUC_overshoot.choice_highE.perHighElevel.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.physical.perf.choice_highE.perHighElevel.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.physical.perf.choice_highE.perHighElevel.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.physical.perf.choice_highE.perHighElevel.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            % mental
            [m_perf_mbSplit.mental.n_errors.choice_highE.perHighElevel.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.mental.n_errors.choice_highE.perHighElevel.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.mental.n_errors.choice_highE.perHighElevel.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.mental.successSpeed.choice_highE.perHighElevel.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.mental.successSpeed.choice_highE.perHighElevel.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.mental.successSpeed.choice_highE.perHighElevel.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.mental.perf.choice_highE.perHighElevel.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.mental.perf.choice_highE.perHighElevel.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.mental.perf.choice_highE.perHighElevel.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
            [m_perf_mbSplit.mental.RT_avg.choice_highE.perHighElevel.(ROI_info_nm).(grp_nm_bis),...
                sem_perf_mbSplit.mental.RT_avg.choice_highE.perHighElevel.(ROI_info_nm).(grp_nm_bis)] = mean_sem_sd(perf.mental.RT_avg.choice_highE.perHighElevel.(ROI_info_nm)(:,met_subs.(grp_nm)), 2);
        end % ROI activity
end % loop median split

%% figures
if dispFig == true
    lWidth = 3;
    black = [0 0 0];
    grey = [143 143 143]./255;
    purple = [153 142 195]./255;
    orange = [241 163 64]./255;
    pSize = 50;
    low_met_nm = ['low_',metabolite_nm];
    high_met_nm = ['high_',metabolite_nm];
    low_met_nm_bis = ['low ',metabolite_nm];
    high_met_nm_bis = ['high ',metabolite_nm];
    
    %% E chosen - grip
    fig;
    
    % latency = f(ROI)
    subplot(2,2,1);
    hold on;
    Ech_lat_low_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.physical.latency.perEch.(['low_',ROI_short_nm]).(low_met_nm),...
        sem_perf_mbSplit.physical.latency.perEch.(['low_',ROI_short_nm]).(low_met_nm));
    Ech_lat_high_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.physical.latency.perEch.(['high_',ROI_short_nm]).(low_met_nm),...
        sem_perf_mbSplit.physical.latency.perEch.(['high_',ROI_short_nm]).(low_met_nm));
    Ech_lat_low_ROI_high_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.physical.latency.perEch.(['low_',ROI_short_nm]).(high_met_nm),...
        sem_perf_mbSplit.physical.latency.perEch.(['low_',ROI_short_nm]).(high_met_nm));
    Ech_lat_high_ROI_high_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.physical.latency.perEch.(['high_',ROI_short_nm]).(high_met_nm),...
        sem_perf_mbSplit.physical.latency.perEch.(['high_',ROI_short_nm]).(high_met_nm));
    % modify curve properties
    Ech_lat_low_ROI_low_met_hdl.LineStyle = '--';
    Ech_lat_low_ROI_low_met_hdl.LineWidth = lWidth;
    Ech_lat_low_ROI_low_met_hdl.Color = purple;
    Ech_lat_high_ROI_low_met_hdl.LineStyle = '--';
    Ech_lat_high_ROI_low_met_hdl.LineWidth = lWidth;
    Ech_lat_high_ROI_low_met_hdl.Color = orange;
    Ech_lat_low_ROI_high_met_hdl.LineStyle = '-';
    Ech_lat_low_ROI_high_met_hdl.LineWidth = lWidth;
    Ech_lat_low_ROI_high_met_hdl.Color = purple;
    Ech_lat_high_ROI_high_met_hdl.LineStyle = '-';
    Ech_lat_high_ROI_high_met_hdl.LineWidth = lWidth;
    Ech_lat_high_ROI_high_met_hdl.Color = orange;
    legend([Ech_lat_low_ROI_low_met_hdl, Ech_lat_high_ROI_low_met_hdl,...
        Ech_lat_low_ROI_high_met_hdl, Ech_lat_high_ROI_high_met_hdl],...
        {['low ',ROI_short_nm,' - low ',metabolite_nm],...
        ['high ',ROI_short_nm,' - low ',metabolite_nm],...
        ['low ',ROI_short_nm,' - high ',metabolite_nm],...
        ['high ',ROI_short_nm,' - high ',metabolite_nm]});
    legend('boxoff');
    legend('Location','NorthWest');
    xticks(Ech_levels);
    xlabel('E chosen');
    ylabel('Latency to squeeze (s)');
    legend_size(pSize);
    
    % force peak = f(ROI)
    subplot(2,2,2);
    hold on;
    Ech_Fpeak_low_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.physical.forcePeak.perEch.(['low_',ROI_short_nm]).(low_met_nm),...
        sem_perf_mbSplit.physical.forcePeak.perEch.(['low_',ROI_short_nm]).(low_met_nm));
    Ech_Fpeak_high_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.physical.forcePeak.perEch.(['high_',ROI_short_nm]).(low_met_nm),...
        sem_perf_mbSplit.physical.forcePeak.perEch.(['high_',ROI_short_nm]).(low_met_nm));
    Ech_Fpeak_low_ROI_high_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.physical.forcePeak.perEch.(['low_',ROI_short_nm]).(high_met_nm),...
        sem_perf_mbSplit.physical.forcePeak.perEch.(['low_',ROI_short_nm]).(high_met_nm));
    Ech_Fpeak_high_ROI_high_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.physical.forcePeak.perEch.(['high_',ROI_short_nm]).(high_met_nm),...
        sem_perf_mbSplit.physical.forcePeak.perEch.(['high_',ROI_short_nm]).(high_met_nm));
    % modify curve properties
    Ech_Fpeak_low_ROI_low_met_hdl.LineStyle = '--';
    Ech_Fpeak_low_ROI_low_met_hdl.LineWidth = lWidth;
    Ech_Fpeak_low_ROI_low_met_hdl.Color = purple;
    Ech_Fpeak_high_ROI_low_met_hdl.LineStyle = '--';
    Ech_Fpeak_high_ROI_low_met_hdl.LineWidth = lWidth;
    Ech_Fpeak_high_ROI_low_met_hdl.Color = orange;
    Ech_Fpeak_low_ROI_high_met_hdl.LineStyle = '-';
    Ech_Fpeak_low_ROI_high_met_hdl.LineWidth = lWidth;
    Ech_Fpeak_low_ROI_high_met_hdl.Color = purple;
    Ech_Fpeak_high_ROI_high_met_hdl.LineStyle = '-';
    Ech_Fpeak_high_ROI_high_met_hdl.LineWidth = lWidth;
    Ech_Fpeak_high_ROI_high_met_hdl.Color = orange;
    legend([Ech_Fpeak_low_ROI_low_met_hdl, Ech_Fpeak_high_ROI_low_met_hdl,...
        Ech_Fpeak_low_ROI_high_met_hdl, Ech_Fpeak_high_ROI_high_met_hdl],...
        {['low ',ROI_short_nm,' - low ',metabolite_nm],...
        ['high ',ROI_short_nm,' - low ',metabolite_nm],...
        ['low ',ROI_short_nm,' - high ',metabolite_nm],...
        ['high ',ROI_short_nm,' - high ',metabolite_nm]});
    legend('boxoff');
    legend('Location','NorthWest');
    xticks(Ech_levels);
    xlabel('E chosen');
    ylabel('Peak force (%)');
    legend_size(pSize);
    
    % AUC force = f(ROI)
    subplot(2,2,3);
    hold on;
    Ech_AUC_low_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.physical.AUC.perEch.(['low_',ROI_short_nm]).(low_met_nm),...
        sem_perf_mbSplit.physical.AUC.perEch.(['low_',ROI_short_nm]).(low_met_nm));
    Ech_AUC_high_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.physical.AUC.perEch.(['high_',ROI_short_nm]).(low_met_nm),...
        sem_perf_mbSplit.physical.AUC.perEch.(['high_',ROI_short_nm]).(low_met_nm));
    Ech_AUC_low_ROI_high_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.physical.AUC.perEch.(['low_',ROI_short_nm]).(high_met_nm),...
        sem_perf_mbSplit.physical.AUC.perEch.(['low_',ROI_short_nm]).(high_met_nm));
    Ech_AUC_high_ROI_high_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.physical.AUC.perEch.(['high_',ROI_short_nm]).(high_met_nm),...
        sem_perf_mbSplit.physical.AUC.perEch.(['high_',ROI_short_nm]).(high_met_nm));
    % modify curve properties
    Ech_AUC_low_ROI_low_met_hdl.LineStyle = '--';
    Ech_AUC_low_ROI_low_met_hdl.LineWidth = lWidth;
    Ech_AUC_low_ROI_low_met_hdl.Color = purple;
    Ech_AUC_high_ROI_low_met_hdl.LineStyle = '--';
    Ech_AUC_high_ROI_low_met_hdl.LineWidth = lWidth;
    Ech_AUC_high_ROI_low_met_hdl.Color = orange;
    Ech_AUC_low_ROI_high_met_hdl.LineStyle = '-';
    Ech_AUC_low_ROI_high_met_hdl.LineWidth = lWidth;
    Ech_AUC_low_ROI_high_met_hdl.Color = purple;
    Ech_AUC_high_ROI_high_met_hdl.LineStyle = '-';
    Ech_AUC_high_ROI_high_met_hdl.LineWidth = lWidth;
    Ech_AUC_high_ROI_high_met_hdl.Color = orange;
    legend([Ech_AUC_low_ROI_low_met_hdl, Ech_AUC_high_ROI_low_met_hdl,...
        Ech_AUC_low_ROI_high_met_hdl, Ech_AUC_high_ROI_high_met_hdl],...
        {['low ',ROI_short_nm,' - low ',metabolite_nm],...
        ['high ',ROI_short_nm,' - low ',metabolite_nm],...
        ['low ',ROI_short_nm,' - high ',metabolite_nm],...
        ['high ',ROI_short_nm,' - high ',metabolite_nm]});
    legend('boxoff');
    legend('Location','NorthWest');
    xticks(Ech_levels);
    xlabel('E chosen');
    ylabel('AUC force');
    legend_size(pSize);
    
    % AUC overshoot force = f(ROI)
    subplot(2,2,4);
    hold on;
    Ech_AUC_overshoot_low_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.physical.AUC_overshoot.perEch.(['low_',ROI_short_nm]).(low_met_nm),...
        sem_perf_mbSplit.physical.AUC_overshoot.perEch.(['low_',ROI_short_nm]).(low_met_nm));
    Ech_AUC_overshoot_high_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.physical.AUC_overshoot.perEch.(['high_',ROI_short_nm]).(low_met_nm),...
        sem_perf_mbSplit.physical.AUC_overshoot.perEch.(['high_',ROI_short_nm]).(low_met_nm));
    Ech_AUC_overshoot_low_ROI_high_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.physical.AUC_overshoot.perEch.(['low_',ROI_short_nm]).(high_met_nm),...
        sem_perf_mbSplit.physical.AUC_overshoot.perEch.(['low_',ROI_short_nm]).(high_met_nm));
    Ech_AUC_overshoot_high_ROI_high_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.physical.AUC_overshoot.perEch.(['high_',ROI_short_nm]).(high_met_nm),...
        sem_perf_mbSplit.physical.AUC_overshoot.perEch.(['high_',ROI_short_nm]).(high_met_nm));
    % modify curve properties
    Ech_AUC_overshoot_low_ROI_low_met_hdl.LineStyle = '--';
    Ech_AUC_overshoot_low_ROI_low_met_hdl.LineWidth = lWidth;
    Ech_AUC_overshoot_low_ROI_low_met_hdl.Color = purple;
    Ech_AUC_overshoot_high_ROI_low_met_hdl.LineStyle = '--';
    Ech_AUC_overshoot_high_ROI_low_met_hdl.LineWidth = lWidth;
    Ech_AUC_overshoot_high_ROI_low_met_hdl.Color = orange;
    Ech_AUC_overshoot_low_ROI_high_met_hdl.LineStyle = '-';
    Ech_AUC_overshoot_low_ROI_high_met_hdl.LineWidth = lWidth;
    Ech_AUC_overshoot_low_ROI_high_met_hdl.Color = purple;
    Ech_AUC_overshoot_high_ROI_high_met_hdl.LineStyle = '-';
    Ech_AUC_overshoot_high_ROI_high_met_hdl.LineWidth = lWidth;
    Ech_AUC_overshoot_high_ROI_high_met_hdl.Color = orange;
    legend([Ech_AUC_overshoot_low_ROI_low_met_hdl, Ech_AUC_overshoot_high_ROI_low_met_hdl,...
        Ech_AUC_overshoot_low_ROI_high_met_hdl, Ech_AUC_overshoot_high_ROI_high_met_hdl],...
        {['low ',ROI_short_nm,' - low ',metabolite_nm],...
        ['high ',ROI_short_nm,' - low ',metabolite_nm],...
        ['low ',ROI_short_nm,' - high ',metabolite_nm],...
        ['high ',ROI_short_nm,' - high ',metabolite_nm]});
    legend('boxoff');
    legend('Location','NorthWest');
    xticks(Ech_levels);
    xlabel('E chosen');
    ylabel('AUC force overshoot');
    legend_size(pSize);
    
    %% E chosen - 2-back
    fig;
    
    % success speed = f(ROI)
    subplot(1,3,1);
    hold on;
    Ech_successSpeed_low_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.mental.successSpeed.perEch.(['low_',ROI_short_nm]).(low_met_nm),...
        sem_perf_mbSplit.mental.successSpeed.perEch.(['low_',ROI_short_nm]).(low_met_nm));
    Ech_successSpeed_high_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.mental.successSpeed.perEch.(['high_',ROI_short_nm]).(low_met_nm),...
        sem_perf_mbSplit.mental.successSpeed.perEch.(['high_',ROI_short_nm]).(low_met_nm));
    Ech_successSpeed_low_ROI_high_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.mental.successSpeed.perEch.(['low_',ROI_short_nm]).(high_met_nm),...
        sem_perf_mbSplit.mental.successSpeed.perEch.(['low_',ROI_short_nm]).(high_met_nm));
    Ech_successSpeed_high_ROI_high_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.mental.successSpeed.perEch.(['high_',ROI_short_nm]).(high_met_nm),...
        sem_perf_mbSplit.mental.successSpeed.perEch.(['high_',ROI_short_nm]).(high_met_nm));
    % modify curve properties
    Ech_successSpeed_low_ROI_low_met_hdl.LineStyle = '--';
    Ech_successSpeed_low_ROI_low_met_hdl.LineWidth = lWidth;
    Ech_successSpeed_low_ROI_low_met_hdl.Color = purple;
    Ech_successSpeed_high_ROI_low_met_hdl.LineStyle = '--';
    Ech_successSpeed_high_ROI_low_met_hdl.LineWidth = lWidth;
    Ech_successSpeed_high_ROI_low_met_hdl.Color = orange;
    Ech_successSpeed_low_ROI_high_met_hdl.LineStyle = '-';
    Ech_successSpeed_low_ROI_high_met_hdl.LineWidth = lWidth;
    Ech_successSpeed_low_ROI_high_met_hdl.Color = purple;
    Ech_successSpeed_high_ROI_high_met_hdl.LineStyle = '-';
    Ech_successSpeed_high_ROI_high_met_hdl.LineWidth = lWidth;
    Ech_successSpeed_high_ROI_high_met_hdl.Color = orange;
    legend([Ech_successSpeed_low_ROI_low_met_hdl, Ech_successSpeed_high_ROI_low_met_hdl,...
        Ech_successSpeed_low_ROI_high_met_hdl, Ech_successSpeed_high_ROI_high_met_hdl],...
        {['low ',ROI_short_nm,' - low ',metabolite_nm],...
        ['high ',ROI_short_nm,' - low ',metabolite_nm],...
        ['low ',ROI_short_nm,' - high ',metabolite_nm],...
        ['high ',ROI_short_nm,' - high ',metabolite_nm]});
    legend('boxoff');
    xticks(Ech_levels);
    xlabel('E chosen');
    ylabel('success speed (s)');
    legend_size(pSize);
    
    % number of errors made = f(ROI)
    subplot(1,3,2);
    hold on;
    Ech_nErrors_low_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.mental.n_errors.perEch.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.n_errors.perEch.(['low_',ROI_short_nm]));
    Ech_nErrors_low_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.mental.n_errors.perEch.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.n_errors.perEch.(['low_',ROI_short_nm]));
    Ech_nErrors_high_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.mental.n_errors.perEch.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.n_errors.perEch.(['high_',ROI_short_nm]));
    Ech_nErrors_high_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.mental.n_errors.perEch.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.n_errors.perEch.(['high_',ROI_short_nm]));
    % modify curve properties
    Ech_nErrors_low_ROI_low_met_hdl.LineStyle = '--';
    Ech_nErrors_low_ROI_low_met_hdl.LineWidth = lWidth;
    Ech_nErrors_low_ROI_low_met_hdl.Color = blue;
    Ech_nErrors_low_ROI_low_met_hdl.LineStyle = '--';
    Ech_nErrors_low_ROI_low_met_hdl.LineWidth = lWidth;
    Ech_nErrors_low_ROI_low_met_hdl.Color = blue;
    Ech_nErrors_high_ROI_low_met_hdl.LineStyle = '-';
    Ech_nErrors_high_ROI_low_met_hdl.LineWidth = lWidth;
    Ech_nErrors_high_ROI_low_met_hdl.Color = purple;
    Ech_nErrors_high_ROI_low_met_hdl.LineStyle = '-';
    Ech_nErrors_high_ROI_low_met_hdl.LineWidth = lWidth;
    Ech_nErrors_high_ROI_low_met_hdl.Color = purple;
    legend([Ech_nErrors_high_ROI_low_met_hdl, Ech_nErrors_low_ROI_low_met_hdl],...
        {['low ',ROI_short_nm,' - low ',metabolite_nm],...
        ['high ',ROI_short_nm,' - low ',metabolite_nm],...
        ['low ',ROI_short_nm,' - high ',metabolite_nm],...
        ['high ',ROI_short_nm,' - high ',metabolite_nm]});
    legend('boxoff');
    xticks(Ech_levels);
    xlabel('E chosen');
    ylabel('Number of errors');
    legend_size(pSize);
    
    % average(RT) = f(ROI)
    subplot(1,3,3);
    hold on;
    Ech_RT_avg_low_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.mental.RT_avg.perEch.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.RT_avg.perEch.(['low_',ROI_short_nm]));
    Ech_RT_avg_low_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.mental.RT_avg.perEch.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.RT_avg.perEch.(['low_',ROI_short_nm]));
    Ech_RT_avg_high_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.mental.RT_avg.perEch.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.RT_avg.perEch.(['high_',ROI_short_nm]));
    Ech_RT_avg_high_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.mental.RT_avg.perEch.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.RT_avg.perEch.(['high_',ROI_short_nm]));
    % modify curve properties
    Ech_RT_avg_low_ROI_low_met_hdl.LineStyle = '--';
    Ech_RT_avg_low_ROI_low_met_hdl.LineWidth = lWidth;
    Ech_RT_avg_low_ROI_low_met_hdl.Color = blue;
    Ech_RT_avg_low_ROI_low_met_hdl.LineStyle = '--';
    Ech_RT_avg_low_ROI_low_met_hdl.LineWidth = lWidth;
    Ech_RT_avg_low_ROI_low_met_hdl.Color = blue;
    Ech_RT_avg_high_ROI_low_met_hdl.LineStyle = '-';
    Ech_RT_avg_high_ROI_low_met_hdl.LineWidth = lWidth;
    Ech_RT_avg_high_ROI_low_met_hdl.Color = purple;
    Ech_RT_avg_high_ROI_low_met_hdl.LineStyle = '-';
    Ech_RT_avg_high_ROI_low_met_hdl.LineWidth = lWidth;
    Ech_RT_avg_high_ROI_low_met_hdl.Color = purple;
    legend([Ech_RT_avg_high_ROI_low_met_hdl, Ech_RT_avg_low_ROI_low_met_hdl],...
        {['low ',ROI_short_nm,' - low ',metabolite_nm],...
        ['high ',ROI_short_nm,' - low ',metabolite_nm],...
        ['low ',ROI_short_nm,' - high ',metabolite_nm],...
        ['high ',ROI_short_nm,' - high ',metabolite_nm]});
    legend('boxoff');
    xticks(Ech_levels);
    xlabel('E chosen');
    ylabel('avg(RT) (s)');
    legend_size(pSize);
    
    %% effort level and choice - grip
    fig;
    
    % latency = f(ROI)
    subplot(2,2,1);
    hold on;
    hE_lowEchoice_lat_lowROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.physical.latency.choice_lowE.perHighElevel.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.physical.latency.choice_lowE.perHighElevel.(['low_',ROI_short_nm]));
    hE_lowEchoice_lat_highROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.physical.latency.choice_lowE.perHighElevel.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.physical.latency.choice_lowE.perHighElevel.(['high_',ROI_short_nm]));
    hE_highEchoice_lat_lowROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.physical.latency.choice_highE.perHighElevel.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.physical.latency.choice_highE.perHighElevel.(['low_',ROI_short_nm]));
    hE_highEchoice_lat_highROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.physical.latency.choice_highE.perHighElevel.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.physical.latency.choice_highE.perHighElevel.(['high_',ROI_short_nm]));
    % modify curve properties
    hE_lowEchoice_lat_lowROI_hdl.LineStyle = '--';
    hE_lowEchoice_lat_lowROI_hdl.LineWidth = lWidth;
    hE_lowEchoice_lat_lowROI_hdl.Color = blue;
    hE_lowEchoice_lat_highROI_hdl.LineStyle = '--';
    hE_lowEchoice_lat_highROI_hdl.LineWidth = lWidth;
    hE_lowEchoice_lat_highROI_hdl.Color = purple;
    hE_highEchoice_lat_lowROI_hdl.LineStyle = '-';
    hE_highEchoice_lat_lowROI_hdl.LineWidth = lWidth;
    hE_highEchoice_lat_lowROI_hdl.Color = blue;
    hE_highEchoice_lat_highROI_hdl.LineStyle = '-';
    hE_highEchoice_lat_highROI_hdl.LineWidth = lWidth;
    hE_highEchoice_lat_highROI_hdl.Color = purple;
    legend([hE_highEchoice_lat_highROI_hdl,...
        hE_highEchoice_lat_lowROI_hdl,...
        hE_lowEchoice_lat_highROI_hdl,...
        hE_lowEchoice_lat_lowROI_hdl],...
        {['hEch - high ',ROI_short_nm],...
        ['hEch - low ',ROI_short_nm],...
        ['lowEch - high ',ROI_short_nm],...
        ['lowEch - low ',ROI_short_nm]});
    legend('boxoff');
    xticks(hE_levels);
    xlabel('high effort level');
    ylabel('Latency to squeeze (s)');
    legend_size(pSize);
    
    % force peak = f(ROI)
    subplot(2,2,2);
    hold on;
    hE_lowEchoice_Fpeak_lowROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.physical.forcePeak.choice_lowE.perHighElevel.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.physical.forcePeak.choice_lowE.perHighElevel.(['low_',ROI_short_nm]));
    hE_lowEchoice_Fpeak_highROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.physical.forcePeak.choice_lowE.perHighElevel.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.physical.forcePeak.choice_lowE.perHighElevel.(['high_',ROI_short_nm]));
    hE_highEchoice_Fpeak_lowROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.physical.forcePeak.choice_highE.perHighElevel.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.physical.forcePeak.choice_highE.perHighElevel.(['low_',ROI_short_nm]));
    hE_highEchoice_Fpeak_highROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.physical.forcePeak.choice_highE.perHighElevel.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.physical.forcePeak.choice_highE.perHighElevel.(['high_',ROI_short_nm]));
    % modify curve properties
    hE_lowEchoice_Fpeak_lowROI_hdl.LineStyle = '--';
    hE_lowEchoice_Fpeak_lowROI_hdl.LineWidth = lWidth;
    hE_lowEchoice_Fpeak_lowROI_hdl.Color = blue;
    hE_lowEchoice_Fpeak_highROI_hdl.LineStyle = '--';
    hE_lowEchoice_Fpeak_highROI_hdl.LineWidth = lWidth;
    hE_lowEchoice_Fpeak_highROI_hdl.Color = purple;
    hE_highEchoice_Fpeak_lowROI_hdl.LineStyle = '-';
    hE_highEchoice_Fpeak_lowROI_hdl.LineWidth = lWidth;
    hE_highEchoice_Fpeak_lowROI_hdl.Color = blue;
    hE_highEchoice_Fpeak_highROI_hdl.LineStyle = '-';
    hE_highEchoice_Fpeak_highROI_hdl.LineWidth = lWidth;
    hE_highEchoice_Fpeak_highROI_hdl.Color = purple;
    legend([hE_highEchoice_Fpeak_highROI_hdl,...
        hE_highEchoice_Fpeak_lowROI_hdl,...
        hE_lowEchoice_Fpeak_highROI_hdl,...
        hE_lowEchoice_Fpeak_lowROI_hdl],...
        {['hEch - high ',ROI_short_nm],...
        ['hEch - low ',ROI_short_nm],...
        ['lowEch - high ',ROI_short_nm],...
        ['lowEch - low ',ROI_short_nm]});
    legend('boxoff');
    xticks(hE_levels);
    xlabel('high effort level');
    ylabel('Peak force (%)');
    legend_size(pSize);
    
    % AUC force = f(ROI)
    subplot(2,2,3);
    hold on;
    hE_lowEchoice_AUC_lowROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.physical.AUC.choice_lowE.perHighElevel.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.physical.AUC.choice_lowE.perHighElevel.(['low_',ROI_short_nm]));
    hE_lowEchoice_AUC_highROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.physical.AUC.choice_lowE.perHighElevel.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.physical.AUC.choice_lowE.perHighElevel.(['high_',ROI_short_nm]));
    hE_highEchoice_AUC_lowROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.physical.AUC.choice_highE.perHighElevel.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.physical.AUC.choice_highE.perHighElevel.(['low_',ROI_short_nm]));
    hE_highEchoice_AUC_highROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.physical.AUC.choice_highE.perHighElevel.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.physical.AUC.choice_highE.perHighElevel.(['high_',ROI_short_nm]));
    % modify curve properties
    hE_lowEchoice_AUC_lowROI_hdl.LineStyle = '--';
    hE_lowEchoice_AUC_lowROI_hdl.LineWidth = lWidth;
    hE_lowEchoice_AUC_lowROI_hdl.Color = blue;
    hE_lowEchoice_AUC_highROI_hdl.LineStyle = '--';
    hE_lowEchoice_AUC_highROI_hdl.LineWidth = lWidth;
    hE_lowEchoice_AUC_highROI_hdl.Color = purple;
    hE_highEchoice_AUC_lowROI_hdl.LineStyle = '-';
    hE_highEchoice_AUC_lowROI_hdl.LineWidth = lWidth;
    hE_highEchoice_AUC_lowROI_hdl.Color = blue;
    hE_highEchoice_AUC_highROI_hdl.LineStyle = '-';
    hE_highEchoice_AUC_highROI_hdl.LineWidth = lWidth;
    hE_highEchoice_AUC_highROI_hdl.Color = purple;
    legend([hE_highEchoice_AUC_highROI_hdl,...
        hE_highEchoice_AUC_lowROI_hdl,...
        hE_lowEchoice_AUC_highROI_hdl,...
        hE_lowEchoice_AUC_lowROI_hdl],...
        {['hEch - high ',ROI_short_nm],...
        ['hEch - low ',ROI_short_nm],...
        ['lowEch - high ',ROI_short_nm],...
        ['lowEch - low ',ROI_short_nm]});
    legend('boxoff');
    xticks(hE_levels);
    xlabel('high effort level');
    ylabel('AUC force');
    legend_size(pSize);
    
    % AUC overshoot force = f(ROI)
    subplot(2,2,4);
    hold on;
    hE_lowEchoice_AUC_overshoot_lowROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.physical.AUC_overshoot.choice_lowE.perHighElevel.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.physical.AUC_overshoot.choice_lowE.perHighElevel.(['low_',ROI_short_nm]));
    hE_lowEchoice_AUC_overshoot_highROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.physical.AUC_overshoot.choice_lowE.perHighElevel.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.physical.AUC_overshoot.choice_lowE.perHighElevel.(['high_',ROI_short_nm]));
    hE_highEchoice_AUC_overshoot_lowROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.physical.AUC_overshoot.choice_highE.perHighElevel.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.physical.AUC_overshoot.choice_highE.perHighElevel.(['low_',ROI_short_nm]));
    hE_highEchoice_AUC_overshoot_highROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.physical.AUC_overshoot.choice_highE.perHighElevel.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.physical.AUC_overshoot.choice_highE.perHighElevel.(['high_',ROI_short_nm]));
    % modify curve properties
    hE_lowEchoice_AUC_overshoot_lowROI_hdl.LineStyle = '--';
    hE_lowEchoice_AUC_overshoot_lowROI_hdl.LineWidth = lWidth;
    hE_lowEchoice_AUC_overshoot_lowROI_hdl.Color = blue;
    hE_lowEchoice_AUC_overshoot_highROI_hdl.LineStyle = '--';
    hE_lowEchoice_AUC_overshoot_highROI_hdl.LineWidth = lWidth;
    hE_lowEchoice_AUC_overshoot_highROI_hdl.Color = purple;
    hE_highEchoice_AUC_overshoot_lowROI_hdl.LineStyle = '-';
    hE_highEchoice_AUC_overshoot_lowROI_hdl.LineWidth = lWidth;
    hE_highEchoice_AUC_overshoot_lowROI_hdl.Color = blue;
    hE_highEchoice_AUC_overshoot_highROI_hdl.LineStyle = '-';
    hE_highEchoice_AUC_overshoot_highROI_hdl.LineWidth = lWidth;
    hE_highEchoice_AUC_overshoot_highROI_hdl.Color = purple;
    legend([hE_highEchoice_AUC_overshoot_highROI_hdl,...
        hE_highEchoice_AUC_overshoot_lowROI_hdl,...
        hE_lowEchoice_AUC_overshoot_highROI_hdl,...
        hE_lowEchoice_AUC_overshoot_lowROI_hdl],...
        {['hEch - high ',ROI_short_nm],...
        ['hEch - low ',ROI_short_nm],...
        ['lowEch - high ',ROI_short_nm],...
        ['lowEch - low ',ROI_short_nm]});
    legend('boxoff');
    xticks(hE_levels);
    xlabel('high effort level');
    ylabel('AUC force overshoot');
    legend_size(pSize);
    
    %% effort level and choice - 2-back
    fig;
    
    % success speed = f(ROI)
    subplot(1,3,1);
    hold on;
    hE_lowEchoice_successSpeed_lowROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.mental.successSpeed.choice_lowE.perHighElevel.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.successSpeed.choice_lowE.perHighElevel.(['low_',ROI_short_nm]));
    hE_lowEchoice_successSpeed_highROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.mental.successSpeed.choice_lowE.perHighElevel.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.successSpeed.choice_lowE.perHighElevel.(['high_',ROI_short_nm]));
    hE_highEchoice_successSpeed_lowROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.mental.successSpeed.choice_highE.perHighElevel.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.successSpeed.choice_highE.perHighElevel.(['low_',ROI_short_nm]));
    hE_highEchoice_successSpeed_highROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.mental.successSpeed.choice_highE.perHighElevel.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.successSpeed.choice_highE.perHighElevel.(['high_',ROI_short_nm]));
    % modify curve properties
    hE_lowEchoice_successSpeed_lowROI_hdl.LineStyle = '--';
    hE_lowEchoice_successSpeed_lowROI_hdl.LineWidth = lWidth;
    hE_lowEchoice_successSpeed_lowROI_hdl.Color = blue;
    hE_lowEchoice_successSpeed_highROI_hdl.LineStyle = '--';
    hE_lowEchoice_successSpeed_highROI_hdl.LineWidth = lWidth;
    hE_lowEchoice_successSpeed_highROI_hdl.Color = purple;
    hE_highEchoice_successSpeed_lowROI_hdl.LineStyle = '-';
    hE_highEchoice_successSpeed_lowROI_hdl.LineWidth = lWidth;
    hE_highEchoice_successSpeed_lowROI_hdl.Color = blue;
    hE_highEchoice_successSpeed_highROI_hdl.LineStyle = '-';
    hE_highEchoice_successSpeed_highROI_hdl.LineWidth = lWidth;
    hE_highEchoice_successSpeed_highROI_hdl.Color = purple;
    legend([hE_highEchoice_successSpeed_highROI_hdl,...
        hE_highEchoice_successSpeed_lowROI_hdl,...
        hE_lowEchoice_successSpeed_highROI_hdl,...
        hE_lowEchoice_successSpeed_lowROI_hdl],...
        {['hEch - high ',ROI_short_nm],...
        ['hEch - low ',ROI_short_nm],...
        ['lowEch - high ',ROI_short_nm],...
        ['lowEch - low ',ROI_short_nm]});
    legend('boxoff');
    xticks(hE_levels);
    xlabel('high effort level');
    ylabel('success speed (s)');
    legend_size(pSize);
    
    % number of errors = f(ROI)
    subplot(1,3,2);
    hold on;
    hE_lowEchoice_nErrors_lowROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.mental.n_errors.choice_lowE.perHighElevel.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.n_errors.choice_lowE.perHighElevel.(['low_',ROI_short_nm]));
    hE_lowEchoice_nErrors_highROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.mental.n_errors.choice_lowE.perHighElevel.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.n_errors.choice_lowE.perHighElevel.(['high_',ROI_short_nm]));
    hE_highEchoice_nErrors_lowROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.mental.n_errors.choice_highE.perHighElevel.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.n_errors.choice_highE.perHighElevel.(['low_',ROI_short_nm]));
    hE_highEchoice_nErrors_highROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.mental.n_errors.choice_highE.perHighElevel.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.n_errors.choice_highE.perHighElevel.(['high_',ROI_short_nm]));
    % modify curve properties
    hE_lowEchoice_nErrors_lowROI_hdl.LineStyle = '--';
    hE_lowEchoice_nErrors_lowROI_hdl.LineWidth = lWidth;
    hE_lowEchoice_nErrors_lowROI_hdl.Color = blue;
    hE_lowEchoice_nErrors_highROI_hdl.LineStyle = '--';
    hE_lowEchoice_nErrors_highROI_hdl.LineWidth = lWidth;
    hE_lowEchoice_nErrors_highROI_hdl.Color = purple;
    hE_highEchoice_nErrors_lowROI_hdl.LineStyle = '-';
    hE_highEchoice_nErrors_lowROI_hdl.LineWidth = lWidth;
    hE_highEchoice_nErrors_lowROI_hdl.Color = blue;
    hE_highEchoice_nErrors_highROI_hdl.LineStyle = '-';
    hE_highEchoice_nErrors_highROI_hdl.LineWidth = lWidth;
    hE_highEchoice_nErrors_highROI_hdl.Color = purple;
    legend([hE_highEchoice_nErrors_highROI_hdl,...
        hE_highEchoice_nErrors_lowROI_hdl,...
        hE_lowEchoice_nErrors_highROI_hdl,...
        hE_lowEchoice_nErrors_lowROI_hdl],...
        {['hEch - high ',ROI_short_nm],...
        ['hEch - low ',ROI_short_nm],...
        ['lowEch - high ',ROI_short_nm],...
        ['lowEch - low ',ROI_short_nm]});
    legend('boxoff');
    xticks(hE_levels);
    xlabel('high effort level');
    ylabel('Number of errors');
    legend_size(pSize);
    
    % RT_avg force = f(ROI)
    subplot(1,3,3);
    hold on;
    hE_lowEchoice_RT_avg_lowROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.mental.RT_avg.choice_lowE.perHighElevel.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.RT_avg.choice_lowE.perHighElevel.(['low_',ROI_short_nm]));
    hE_lowEchoice_RT_avg_highROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.mental.RT_avg.choice_lowE.perHighElevel.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.RT_avg.choice_lowE.perHighElevel.(['high_',ROI_short_nm]));
    hE_highEchoice_RT_avg_lowROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.mental.RT_avg.choice_highE.perHighElevel.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.RT_avg.choice_highE.perHighElevel.(['low_',ROI_short_nm]));
    hE_highEchoice_RT_avg_highROI_hdl = errorbar(hE_levels,...
        m_perf_mbSplit.mental.RT_avg.choice_highE.perHighElevel.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.RT_avg.choice_highE.perHighElevel.(['high_',ROI_short_nm]));
    % modify curve properties
    hE_lowEchoice_RT_avg_lowROI_hdl.LineStyle = '--';
    hE_lowEchoice_RT_avg_lowROI_hdl.LineWidth = lWidth;
    hE_lowEchoice_RT_avg_lowROI_hdl.Color = blue;
    hE_lowEchoice_RT_avg_highROI_hdl.LineStyle = '--';
    hE_lowEchoice_RT_avg_highROI_hdl.LineWidth = lWidth;
    hE_lowEchoice_RT_avg_highROI_hdl.Color = purple;
    hE_highEchoice_RT_avg_lowROI_hdl.LineStyle = '-';
    hE_highEchoice_RT_avg_lowROI_hdl.LineWidth = lWidth;
    hE_highEchoice_RT_avg_lowROI_hdl.Color = blue;
    hE_highEchoice_RT_avg_highROI_hdl.LineStyle = '-';
    hE_highEchoice_RT_avg_highROI_hdl.LineWidth = lWidth;
    hE_highEchoice_RT_avg_highROI_hdl.Color = purple;
    legend([hE_highEchoice_RT_avg_highROI_hdl,...
        hE_highEchoice_RT_avg_lowROI_hdl,...
        hE_lowEchoice_RT_avg_highROI_hdl,...
        hE_lowEchoice_RT_avg_lowROI_hdl],...
        {['hEch - high ',ROI_short_nm],...
        ['hEch - low ',ROI_short_nm],...
        ['lowEch - high ',ROI_short_nm],...
        ['lowEch - low ',ROI_short_nm]});
    legend('boxoff');
    xticks(hE_levels);
    xlabel('high effort level');
    ylabel('avg(RT) (s)');
    legend_size(pSize);
    
    %% Performance (%) for each task
    fig;
    
    % Performance (physical) = f(ROI)
    subplot(1,2,1);
    hold on;
    perf_low_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.physical.perf.perEch.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.physical.perf.perEch.(['low_',ROI_short_nm]));
    perf_high_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.physical.perf.perEch.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.physical.perf.perEch.(['high_',ROI_short_nm]));
    % modify curve properties
    perf_low_ROI_low_met_hdl.LineStyle = '--';
    perf_low_ROI_low_met_hdl.LineWidth = lWidth;
    perf_low_ROI_low_met_hdl.Color = blue;
    perf_high_ROI_low_met_hdl.LineStyle = '-';
    perf_high_ROI_low_met_hdl.LineWidth = lWidth;
    perf_high_ROI_low_met_hdl.Color = purple;
    legend([perf_high_ROI_low_met_hdl, perf_low_ROI_low_met_hdl],...
        {['low ',ROI_short_nm,' - low ',metabolite_nm],...
        ['high ',ROI_short_nm,' - low ',metabolite_nm],...
        ['low ',ROI_short_nm,' - high ',metabolite_nm],...
        ['high ',ROI_short_nm,' - high ',metabolite_nm]});
    legend('boxoff');
    legend('Location','SouthWest');
    xticks(Ech_levels);
    xlabel('E chosen');
    ylabel('Performance (%) - Physical task');
    legend_size(pSize);
    
    % Performance (mental) = f(ROI)
    subplot(1,2,2);
    hold on;
    perf_low_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.mental.perf.perEch.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.perf.perEch.(['low_',ROI_short_nm]));
    perf_low_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.mental.perf.perEch.(['low_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.perf.perEch.(['low_',ROI_short_nm]));
    perf_high_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.mental.perf.perEch.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.perf.perEch.(['high_',ROI_short_nm]));
    perf_high_ROI_low_met_hdl = errorbar(Ech_levels,...
        m_perf_mbSplit.mental.perf.perEch.(['high_',ROI_short_nm]),...
        sem_perf_mbSplit.mental.perf.perEch.(['high_',ROI_short_nm]));
    % modify curve properties
    perf_low_ROI_low_met_hdl.LineStyle = '--';
    perf_low_ROI_low_met_hdl.LineWidth = lWidth;
    perf_low_ROI_low_met_hdl.Color = blue;
    perf_low_ROI_low_met_hdl.LineStyle = '--';
    perf_low_ROI_low_met_hdl.LineWidth = lWidth;
    perf_low_ROI_low_met_hdl.Color = blue;
    perf_high_ROI_low_met_hdl.LineStyle = '-';
    perf_high_ROI_low_met_hdl.LineWidth = lWidth;
    perf_high_ROI_low_met_hdl.Color = purple;
    perf_high_ROI_low_met_hdl.LineStyle = '-';
    perf_high_ROI_low_met_hdl.LineWidth = lWidth;
    perf_high_ROI_low_met_hdl.Color = purple;
    legend([perf_high_ROI_low_met_hdl, perf_low_ROI_low_met_hdl],...
        {['low ',ROI_short_nm,' - low ',metabolite_nm],...
        ['high ',ROI_short_nm,' - low ',metabolite_nm],...
        ['low ',ROI_short_nm,' - high ',metabolite_nm],...
        ['high ',ROI_short_nm,' - high ',metabolite_nm]});
    legend('boxoff');
    legend('Location','SouthWest');
    xticks(Ech_levels);
    xlabel('E chosen');
    ylabel('Performance (%) - Mental task');
    legend_size(pSize);
end % display figure